import { WmoCodeInfo } from '../types/weather';

export const WMO_CODES: Record<number, WmoCodeInfo> = {
  0: {
    code: 0,
    label: 'Clear Sky',
    description: 'Cloudless skies with full solar irradiance',
    iconName: 'Sun',
    severity: 'clear',
    badgeBg: 'bg-amber-500/10 border-amber-500/30 text-amber-400',
    badgeText: 'Clear',
  },
  1: {
    code: 1,
    label: 'Mainly Clear',
    description: 'Mostly clear with minor high clouds',
    iconName: 'SunMedium',
    severity: 'clear',
    badgeBg: 'bg-amber-500/10 border-amber-500/30 text-amber-300',
    badgeText: 'Mainly Clear',
  },
  2: {
    code: 2,
    label: 'Partly Cloudy',
    description: 'Scattered clouds with periodic sun',
    iconName: 'CloudSun',
    severity: 'cloudy',
    badgeBg: 'bg-sky-500/10 border-sky-500/30 text-sky-300',
    badgeText: 'Partly Cloudy',
  },
  3: {
    code: 3,
    label: 'Overcast',
    description: 'Dense cloud cover blocking direct sunlight',
    iconName: 'Cloud',
    severity: 'cloudy',
    badgeBg: 'bg-slate-500/10 border-slate-500/30 text-slate-300',
    badgeText: 'Overcast',
  },
  45: {
    code: 45,
    label: 'Foggy',
    description: 'Reduced surface visibility due to ground fog',
    iconName: 'CloudFog',
    severity: 'fog',
    badgeBg: 'bg-teal-500/10 border-teal-500/30 text-teal-300',
    badgeText: 'Fog',
  },
  48: {
    code: 48,
    label: 'Depositing Rime Fog',
    description: 'Freezing fog forming ice crusts on surfaces',
    iconName: 'CloudFog',
    severity: 'fog',
    badgeBg: 'bg-teal-500/15 border-teal-400/30 text-teal-200',
    badgeText: 'Rime Fog',
  },
  51: {
    code: 51,
    label: 'Light Drizzle',
    description: 'Very light precipitation with fine droplets',
    iconName: 'CloudDrizzle',
    severity: 'rain',
    badgeBg: 'bg-blue-500/10 border-blue-500/30 text-blue-300',
    badgeText: 'Light Drizzle',
  },
  53: {
    code: 53,
    label: 'Moderate Drizzle',
    description: 'Steady fine drizzle affecting visibility',
    iconName: 'CloudDrizzle',
    severity: 'rain',
    badgeBg: 'bg-blue-500/15 border-blue-500/40 text-blue-300',
    badgeText: 'Drizzle',
  },
  55: {
    code: 55,
    label: 'Dense Drizzle',
    description: 'Heavy drizzle with high humidity accumulation',
    iconName: 'CloudDrizzle',
    severity: 'rain',
    badgeBg: 'bg-blue-500/20 border-blue-400/50 text-blue-200',
    badgeText: 'Dense Drizzle',
  },
  56: {
    code: 56,
    label: 'Freezing Drizzle',
    description: 'Light drizzle freezing on contact with ground',
    iconName: 'CloudSnow',
    severity: 'rain',
    badgeBg: 'bg-cyan-500/15 border-cyan-400/40 text-cyan-200',
    badgeText: 'Freezing Drizzle',
  },
  57: {
    code: 57,
    label: 'Dense Freezing Drizzle',
    description: 'Heavy drizzle freezing on contact, slick conditions',
    iconName: 'CloudSnow',
    severity: 'rain',
    badgeBg: 'bg-cyan-500/20 border-cyan-400/50 text-cyan-200',
    badgeText: 'Dense Freezing Drizzle',
  },
  61: {
    code: 61,
    label: 'Slight Rain',
    description: 'Light rain showers with minimal surface pooling',
    iconName: 'CloudRain',
    severity: 'rain',
    badgeBg: 'bg-blue-500/15 border-blue-500/30 text-blue-300',
    badgeText: 'Slight Rain',
  },
  63: {
    code: 63,
    label: 'Moderate Rain',
    description: 'Continuous moderate rainfall',
    iconName: 'CloudRain',
    severity: 'rain',
    badgeBg: 'bg-blue-600/20 border-blue-500/40 text-blue-200',
    badgeText: 'Moderate Rain',
  },
  65: {
    code: 65,
    label: 'Heavy Rain',
    description: 'Intense rain with potential surface run-off',
    iconName: 'CloudRainWind',
    severity: 'rain',
    badgeBg: 'bg-blue-700/30 border-blue-400/60 text-blue-100',
    badgeText: 'Heavy Rain',
  },
  66: {
    code: 66,
    label: 'Light Freezing Rain',
    description: 'Rain freezing instantly on exposed infrastructure',
    iconName: 'CloudSnow',
    severity: 'rain',
    badgeBg: 'bg-cyan-600/20 border-cyan-400/50 text-cyan-200',
    badgeText: 'Freezing Rain',
  },
  67: {
    code: 67,
    label: 'Heavy Freezing Rain',
    description: 'Severe freezing rain leading to rapid ice accumulation',
    iconName: 'CloudSnow',
    severity: 'rain',
    badgeBg: 'bg-cyan-700/30 border-cyan-300/60 text-cyan-100',
    badgeText: 'Heavy Freezing Rain',
  },
  71: {
    code: 71,
    label: 'Slight Snow Fall',
    description: 'Light snowfall with light surface dusting',
    iconName: 'Snowflake',
    severity: 'snow',
    badgeBg: 'bg-sky-400/15 border-sky-300/40 text-sky-200',
    badgeText: 'Slight Snow',
  },
  73: {
    code: 73,
    label: 'Moderate Snow Fall',
    description: 'Steady snowfall accumulating on surfaces',
    iconName: 'Snowflake',
    severity: 'snow',
    badgeBg: 'bg-sky-400/25 border-sky-300/50 text-sky-100',
    badgeText: 'Moderate Snow',
  },
  75: {
    code: 75,
    label: 'Heavy Snow Fall',
    description: 'Heavy snowfall reducing visibility drastically',
    iconName: 'Snowflake',
    severity: 'snow',
    badgeBg: 'bg-indigo-500/30 border-indigo-300/60 text-indigo-100',
    badgeText: 'Heavy Snow',
  },
  77: {
    code: 77,
    label: 'Snow Grains',
    description: 'Frozen ice grains or small snow pellets',
    iconName: 'Snowflake',
    severity: 'snow',
    badgeBg: 'bg-sky-500/20 border-sky-400/40 text-sky-200',
    badgeText: 'Snow Grains',
  },
  80: {
    code: 80,
    label: 'Slight Rain Showers',
    description: 'Intermittent light rain showers',
    iconName: 'CloudRain',
    severity: 'rain',
    badgeBg: 'bg-blue-500/15 border-blue-400/30 text-blue-300',
    badgeText: 'Rain Showers',
  },
  81: {
    code: 81,
    label: 'Moderate Rain Showers',
    description: 'Frequent moderate rainfall bursts',
    iconName: 'CloudRain',
    severity: 'rain',
    badgeBg: 'bg-blue-600/20 border-blue-400/40 text-blue-200',
    badgeText: 'Moderate Showers',
  },
  82: {
    code: 82,
    label: 'Violent Rain Showers',
    description: 'Torrential downpours with heavy flash rainfall',
    iconName: 'CloudRainWind',
    severity: 'rain',
    badgeBg: 'bg-indigo-600/30 border-indigo-400/60 text-indigo-100',
    badgeText: 'Violent Showers',
  },
  85: {
    code: 85,
    label: 'Slight Snow Showers',
    description: 'Brief passing snow showers',
    iconName: 'Snowflake',
    severity: 'snow',
    badgeBg: 'bg-sky-500/15 border-sky-400/30 text-sky-200',
    badgeText: 'Snow Showers',
  },
  86: {
    code: 86,
    label: 'Heavy Snow Showers',
    description: 'Intense snow squalls with severe gusting',
    iconName: 'Snowflake',
    severity: 'snow',
    badgeBg: 'bg-indigo-600/30 border-indigo-400/60 text-indigo-100',
    badgeText: 'Heavy Snow Squall',
  },
  95: {
    code: 95,
    label: 'Thunderstorm',
    description: 'Slight to moderate thunderstorm activity',
    iconName: 'CloudLightning',
    severity: 'storm',
    badgeBg: 'bg-purple-500/20 border-purple-400/50 text-purple-200',
    badgeText: 'Thunderstorm',
  },
  96: {
    code: 96,
    label: 'Thunderstorm with Hail',
    description: 'Thunderstorm accompanied by small hail',
    iconName: 'CloudLightning',
    severity: 'storm',
    badgeBg: 'bg-purple-600/30 border-purple-300/60 text-purple-100',
    badgeText: 'Storm + Hail',
  },
  99: {
    code: 99,
    label: 'Heavy Thunderstorm with Hail',
    description: 'Severe thunderstorm with heavy hail damage risk',
    iconName: 'CloudLightning',
    severity: 'storm',
    badgeBg: 'bg-red-600/30 border-red-400/60 text-red-100',
    badgeText: 'Severe Hailstorm',
  },
};

export function getWmoInfo(code: number, isDay: number = 1): WmoCodeInfo {
  const info = WMO_CODES[code];
  if (info) {
    if (!isDay && info.iconName === 'Sun') {
      return { ...info, iconName: 'Moon' };
    }
    if (!isDay && info.iconName === 'CloudSun') {
      return { ...info, iconName: 'CloudMoon' };
    }
    return info;
  }
  return {
    code,
    label: 'Unknown Weather',
    description: 'Unspecified weather code',
    iconName: 'Cloud',
    severity: 'cloudy',
    badgeBg: 'bg-slate-500/10 border-slate-500/30 text-slate-300',
    badgeText: `Code ${code}`,
  };
}
